[package]
name = "pf-prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pf-engine = { git = "https://github.com/SaphiraKai/powderfell" }
