[package]
name = "pf-prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
pf-engine = { path = "../pf-engine" }
rand = "0.8.5"
show-image = "0.13.1"
